import{a as S,S as E,i as l}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P="55002165-1e4f2080ce8b2f6cba85ff2b5",q="https://pixabay.com/api/",M=15;async function f(r,o){return(await S.get(q,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:M}})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),g=new E(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map($).join("");m.insertAdjacentHTML("beforeend",o),g.refresh()}function $({webformatURL:r,largeImageURL:o,tags:s,likes:a,views:e,comments:t,downloads:n}){return`
<li class="gallery-item">
  <a href="${o}">
    <img src="${r}" alt="${s}" />
  </a>
  <div class="info">
    <p><b>Likes</b><br><span class="value">${a}</span></p>
    <p><b>Views</b><br><span class="value">${e}</span></p>
    <p><b>Comments</b><br><span class="value">${t}</span></p>
    <p><b>Downloads</b><br><span class="value">${n}</span></p>
  </div>
</li>`}function B(){m.innerHTML="",g.refresh()}function b(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}function D(){y.classList.add("visible")}function v(){y.classList.remove("visible")}const A=document.querySelector(".form"),u=document.querySelector(".load-more");let i=1,c="",d=0;const w=15;A.addEventListener("submit",O);u.addEventListener("click",_);async function O(r){if(r.preventDefault(),c=new FormData(r.target).get("search-text").trim(),!!c){i=1,B(),v(),b();try{const s=await f(c,i);if(d=s.totalHits,s.hits.length===0){l.error({message:"Sorry, no images found."});return}h(s.hits),d>w&&D()}catch{l.error({message:"Error fetching images."})}finally{L()}}}async function _(){i+=1,u.disabled=!0,b();try{const r=await f(c,i);h(r.hits);const o=Math.ceil(d/w);i>=o&&(v(),l.info({message:"We're sorry, but you've reached the end of search results."}));const s=document.querySelector(".gallery-item"),{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{l.error({message:"Error loading more images."})}finally{L(),u.disabled=!1}}
//# sourceMappingURL=index.js.map
