import{a as w,S as E,i}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q="55002165-1e4f2080ce8b2f6cba85ff2b5",P="https://pixabay.com/api/",M=15;async function m(r,o){return(await w.get(P,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:M}})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),g=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map($).join("");p.insertAdjacentHTML("beforeend",o),g.refresh()}function $({webformatURL:r,largeImageURL:o,tags:s,likes:a,views:e,comments:t,downloads:n}){return`
<li class="gallery-item">
  <a href="${o}">
    <img src="${r}" alt="${s}" />
  </a>
  <div class="info">
    <p><b>Likes</b><br><span class="value">${a}</span></p>
    <p><b>Views</b><br><span class="value">${e}</span></p>
    <p><b>Comments</b><br><span class="value">${t}</span></p>
    <p><b>Downloads</b><br><span class="value">${n}</span></p>
  </div>
</li>`}function B(){p.innerHTML="",g.refresh()}function L(){y.classList.add("visible")}function v(){y.classList.remove("visible")}function S(){h.classList.add("visible")}function d(){h.classList.remove("visible")}const D=document.querySelector(".form"),A=document.querySelector(".load-more");document.querySelector(".loader");let c=1,l="",f=0;const u=15;D.addEventListener("submit",O);A.addEventListener("click",_);async function O(r){if(r.preventDefault(),l=new FormData(r.target).get("search-text").trim(),!!l){c=1,B(),d(),L();try{const s=await m(l,c,u);if(f=s.totalHits,s.hits.length===0){i.error({message:"Sorry, no images found."});return}b(s.hits),f>u?S():i.info({message:"We're sorry, but you've reached the end of search results."})}catch{i.error({message:"Error fetching images."})}finally{v()}}}async function _(){d(),L();try{c+=1;const r=await m(l,c,u);b(r.hits);const o=Math.ceil(f/u);c>=o?(d(),i.info({message:"We're sorry, but you've reached the end of search results."})):S();const s=document.querySelector(".gallery-item");if(s){const{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch{i.error({message:"Error loading more images."})}finally{v()}}
//# sourceMappingURL=index.js.map
