import{a as S,S as E,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="55002165-1e4f2080ce8b2f6cba85ff2b5",q="https://pixabay.com/api/",M=15;async function f(t,o){return(await S.get(q,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:M}})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),y=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const o=t.map($).join("");m.insertAdjacentHTML("beforeend",o),y.refresh()}function $({webformatURL:t,largeImageURL:o,tags:s,likes:a,views:e,comments:r,downloads:i}){return`
<li class="gallery-item">
  <a href="${o}">
    <img src="${t}" alt="${s}" />
  </a>
  <div class="info">
    <p><b>Likes</b><br><span class="value">${a}</span></p>
    <p><b>Views</b><br><span class="value">${e}</span></p>
    <p><b>Comments</b><br><span class="value">${r}</span></p>
    <p><b>Downloads</b><br><span class="value">${i}</span></p>
  </div>
</li>`}function B(){m.innerHTML="",y.refresh()}function b(){p.classList.add("is-visible")}function L(){p.classList.remove("is-visible")}function v(){h.classList.add("visible")}function u(){h.classList.remove("visible")}const D=document.querySelector(".form"),A=document.querySelector(".load-more");let c=1,l="",d=0;const w=15;D.addEventListener("submit",O);A.addEventListener("click",_);async function O(t){if(t.preventDefault(),l=new FormData(t.target).get("search-text").trim(),!!l){c=1,B(),u(),b();try{const s=await f(l,c);if(d=s.totalHits,s.hits.length===0){n.error({message:"Sorry, no images found."});return}g(s.hits),d>w?v():(u(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Error fetching images."})}finally{L()}}}async function _(){u(),b();try{c+=1;const t=await f(l,c);if(t.hits.length===0){n.info({message:"We're sorry, but you've reached the end of search results."});return}g(t.hits);const o=Math.ceil(d/w);c>=o?(u(),n.info({message:"We're sorry, but you've reached the end of search results."})):v();const s=document.querySelector(".gallery-item");if(s){const{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({message:"Error loading more images."})}finally{L()}}
//# sourceMappingURL=index.js.map
